global:
  scrape_interval: 3s
  external_labels:
    monitor: "monitor"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "monitor"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus-nats-exporter:7777"]
