services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nats_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testing -d iot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  nats_network:
    driver: bridge
